VectorWiki/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wiki.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.PostListView.as_view(), name='postmodel_list'),
     path('post/<slug:slug>', views.PostDetailView.as_view(), name='postmodel_detail'),
     path('post-update/<slug:slug>', views.PostEditView.as_view(), name='postmodel_update'),
     path('post-create/', views.PostCreateView.as_view(), name='postmodel_create'),
     path('post-delete/<slug:slug>', views.PostDeleteView.as_view(), name='postmodel_delete'),
     path('group-create/', views.GroupCreateView.as_view(), name='groupmodel_create'),
     path('group-update/<int:pk>', views.GroupEditView.as_view(), name='groupmodel_update'),
     path('group-delete/<int:pk>', views.GroupDeleteView.as_view(), name='groupmodel_delete'),
     path('phone-create/', views.PhoneCreateView.as_view(), name='phonemodel_create'),
     path('phone-update/<int:pk>', views.PhoneEditView.as_view(), name='phonemodel_update'),
     path('phone-delete/<int:pk>', views.PhoneDeleteView.as_view(), name='phonemodel_delete'),
     path("search/", views.SearchView.as_view(), name='search'),
]

wiki/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from pytils.translit import slugify

class PostModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    title = models.CharField('Название статьи', max_length=150)
    img = models.ImageField('Логотип', upload_to='images/', default='images/images.jpg')
    slug = models.SlugField('Сылка поста', max_length=150, unique=True)
    description = models.TextField('Описание')
    date_create = models.DateTimeField('Дата создания', auto_now_add=True, blank=True)
    date_update = models.DateTimeField('Дата изменения', auto_now=True, blank=True)
    draft = models.BooleanField('Опубликовать', default=True)
    border = models.BooleanField('Доска', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('postmodel_detail', kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(PostModel, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class GroupModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    name = models.CharField('Название группы', max_length=150)
    date_create = models.DateTimeField('Дата создания', auto_now_add=True, blank=True)
    date_update = models.DateTimeField('Дата изменения', auto_now=True, blank=True)
    draft = models.BooleanField('Опубликовать', default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class PhoneModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    name = models.CharField('Имя контакта', max_length=150)
    group = models.ForeignKey(GroupModel, verbose_name='Група контактов', on_delete=models.CASCADE)
    email = models.EmailField('Email адрес', blank=True)
    phone = models.CharField('Номер телефона', max_length=13)
    date_create = models.DateTimeField('Дата создания', auto_now_add=True, blank=True)
    date_update = models.DateTimeField('Дата изменения', auto_now=True, blank=True)
    draft = models.BooleanField('Опубликовать', default=True)

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

wiki/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from .models import PostModel, GroupModel, PhoneModel

class PostForm(forms.ModelForm):
    description = forms.CharField(label='Описание', widget=CKEditorUploadingWidget())

    class Meta:
        model = PostModel
        fields = ['title', 'img', 'description', 'border']


class GroupForm(forms.ModelForm):

    class Meta:
        model = GroupModel
        fields = ['name', ]

class PhoneForm(forms.ModelForm):

    class Meta:
        model = PhoneModel
        exclude = ['date_create', 'date_update', 'user']

wiki/views.py
from allauth.account.views import RedirectAuthenticatedUserMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from .models import PostModel, GroupModel, PhoneModel
from .forms import PostForm, GroupForm, PhoneForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


class Phone:
    def get_phone(self):
        return GroupModel.objects.all()


class Desk:
    def get_desk(self):
        return PostModel.objects.filter(border=True, draft=True)


class Post:
    def get_post(self):
        return PostModel.objects.filter(border=False, draft=True)


class PostListView(LoginRequiredMixin, ListView, Phone, Post, Desk):
    queryset = PostModel.objects.filter(draft=True, border=False)[:3]
    # template_name = 'wiki/index.html'


class PostDetailView(LoginRequiredMixin, DetailView, Phone, Post):
    model = PostModel
    template_name = 'wiki/detail.html'
    slug_field = 'slug'


class PostCreateView(CreateView, Post, Phone):
    model = PostModel
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostEditView(UpdateView, Phone, Post):
    model = PostModel
    form_class = PostForm


class PostDeleteView(DeleteView, Phone, Post):
    model = PostModel
    success_url = reverse_lazy('postmodel_list')


class GroupCreateView(CreateView, Post, Phone):
    model = GroupModel
    form_class = GroupForm
    template_name = 'wiki/postmodel_form.html'
    success_url = reverse_lazy('postmodel_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class GroupEditView(UpdateView, Phone, Post):
    model = GroupModel
    form_class = GroupForm
    success_url = reverse_lazy('postmodel_list')
    template_name = 'wiki/postmodel_form.html'


class GroupDeleteView(DeleteView, Phone, Post):
    model = GroupModel
    success_url = reverse_lazy('postmodel_list')


class PhoneCreateView(CreateView, Post, Phone):
    model = PhoneModel
    form_class = PhoneForm
    template_name = 'wiki/postmodel_form.html'
    success_url = reverse_lazy('postmodel_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PhoneEditView(UpdateView, Phone, Post):
    model = PhoneModel
    form_class = PhoneForm
    success_url = reverse_lazy('postmodel_list')
    template_name = 'wiki/postmodel_form.html'


class PhoneDeleteView(DeleteView, Phone, Post):
    model = PhoneModel
    success_url = reverse_lazy('postmodel_list')


class SearchView(ListView, Phone, Post, LoginRequiredMixin):

    # template_name = 'wiki/search.html'
    paginate_by = 3

    def get_queryset(self): # new
        query = self.request.GET.get('q', None)
        if query is not None:
            object_list = PostModel.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
            return object_list

templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Andrea - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">
    
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/ionicons.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="css/flaticon.css">
    <link rel="stylesheet" href="css/icomoon.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight">
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
					<li><a href="wiki/index.html">Home</a></li>
					<li><a href="fashion.html">Fashion</a></li>
					<li><a href="travel.html">Travel</a></li>
					<li class="colorlib-active"><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>

			<div class="colorlib-footer">
				<h1 id="colorlib-logo" class="mb-5"><a href="wiki/index.html" style="background-image: url(images/bg_1.jpg);">Andrea <span>Moore</span></a></h1>
				<p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
	  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
			</div>
		</aside> <!-- END COLORLIB-ASIDE -->
		<div id="colorlib-main">
			<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
	    	<div class="container-fluid px-0">
	    		<div class="row d-flex">
	    			<div class="col-md-6 d-flex">
	    				<div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url(images/about.jpg);">
	    				</div>
	    			</div>
	    			<div class="col-md-6 d-flex align-items-center">
	    				<div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
		            <h2 class="mb-4">I'm <span>Andrea Moore</span> a Scotish Blogger &amp; Explorer</h2>
		            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
	            </div>
		        </div>
	        </div>
	    	</div>
	    </section>
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="js/jquery.min.js"></script>
  <script src="js/jquery-migrate-3.0.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/jquery.waypoints.min.js"></script>
  <script src="js/jquery.stellar.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.magnific-popup.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/jquery.animateNumber.min.js"></script>
  <script src="js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>
  <script src="js/main.js"></script>
    
  </body>
</html>

templates/base.html
{% load static %}
{% load account %}
{% load i18n %}
{% load account socialaccount %}
<!DOCTYPE html>
<html lang="en">
{% include 'include/head.html' %}
<body>

<div id="colorlib-page">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    <aside id="colorlib-aside" role="complementary" class="js-fullheight">

        {% include 'include/mainmenu.html' %}

        {% include 'include/footer.html' %}

    </aside> <!-- END COLORLIB-ASIDE -->
    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    {% block content %}
                    {% endblock content %}
                    {% include 'include/sidebar.html' %}
                </div>
            </div>
        </section>
    </div><!-- END COLORLIB-MAIN -->
</div><!-- END COLORLIB-PAGE -->

<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "js/jquery.waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.stellar.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/aos.js" %}"></script>
<script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
<script src="{% static "js/scrollax.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static "js/google-map.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>

<script>
    // Get the modal
    var modal = document.getElementById("myModalLogin");

    // Get the button that opens the modal
    var btn = document.getElementsByClassName("myBtn")

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close");

    // When the user clicks on the button, open the modal
    function buttonClick(event) {
        var id = this.getAttribute('data-modal');
        var modal = document.getElementById(id);
        modal.style.display = 'block';
    }

    for (var i = 0; i < btn.length; i++) {
        btn[i].onclick = buttonClick;
    }

    // When the user clicks on <span> (x), close the modal
    function spanClick() {
        var id = this.getAttribute('data-modal');
        var modal = document.getElementById(id);
        modal.style.display = 'none';
    }

    for (var i = 0; i < span.length; i++) {
        span[i].onclick = spanClick;
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        var isModal = (' ' + event.target.className + ' ').indexOf(' modal ') > -1;
        if (isModal) {
            event.target.style.display = "none";
        }
    }
</script>


</body>
</html>

templates/include/footer.html
<div class="colorlib-footer">
    <p class="pfooter"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website made <i class="icon-heart" aria-hidden="true"></i>
        by <a target="_blank">Pirat</a>
    </p>
</div>

templates/include/head.html
{% load static %}

<head>
    <title>Vector Wiki</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">

    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

templates/include/mainmenu.html
{% load account %}
<nav id="colorlib-main-menu" role="navigation">

    {% if user.is_authenticated %}
        <p> {% user_display user %}
            <span>|</span>
            <a href="#" class="myBtn" data-modal="myModal1"> Выйти</a></p>
        {#    {% else %}#}
        {#        <p><a href="#" class="myBtn" data-modal="myModal2">Войти </a>#}
        {#            <span>|</span>#}
        {#        <a href="#" class="myBtn" data-modal="myModal3">Регистрация</a></p>#}
        <!-- The Modal -->
        {#    <div id="myModal2" class="modal">#}
        {#        <!-- Modal content -->#}
        {#        <div class="modal-content">#}
        {#            <div class="modal-header">#}
        {#                <h4>Войти</h4>#}
        {#                <span class="close" data-modal="myModal2">&times;</span>#}
        {#            </div>#}
        {#            <form action="{% url 'account_login' %}" method="post">#}
        {#                {% csrf_token %}#}
        {##}
        {#                <p><input type="hidden" name="next" value="{{ request.get_full_path }}"/></p>#}
        {#                <p><input id="id_login" name="login"#}
        {#                                                                          placeholder="Username or e-mail" type="text"#}
        {#                                                                          required/></p>#}
        {#                <p><input id="id_password" name="password"#}
        {#                                                                   placeholder="Password" type="password" required/></p>#}
        {#                <p><label for="id_remember">Запомнить меня: </label> <input id="id_remember" name="remember"#}
        {#                                                                            type="checkbox"/></p>#}
        {##}
        {#                <p>#}
        {#                    <a href="{% url 'account_reset_password' %}">Забыл пароль? </a>#}
        {#                    <button type="submit">Войти</button>#}
        {#                </p>#}
        {##}
        {#            </form>#}
        {#        </div>#}
        {#    </div>#}

        <div id="myModal1" class="modal">
            <!-- Modal content -->
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Выйти</h4>
                    <span class="close" data-modal="myModal1">&times;</span>
                </div>
                <p>Вы уверены, что хотите выйти?</p>
                <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                    {% endif %}
                    <button type="submit">Выйти</button>
                </form>
            </div>
        </div>

        {#    <div id="myModal3" class="modal">#}
        {#        <!-- Modal content -->#}
        {#        <div class="modal-content">#}
        {#            <div class="modal-header">#}
        {#                <h4>Регистрация</h4>#}
        {#                <span class="close" data-modal="myModal3">&times;</span>#}
        {#            </div>#}
        {#            <p>Уже есть аккаунт? Тогда пожалуйста#}
        {#                <a href="{% url 'account_login' %}">Войдите</a></p>#}
        {#            <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">#}
        {#                {% csrf_token %}#}
        {#                <p><input type="text" name="username"#}
        {#                                                                             placeholder="Имя пользователя"#}
        {#                                                                             autofocus="autofocus" minlength="5"#}
        {#                                                                             maxlength="150" required=""#}
        {#                                                                             id="id_username"></p>#}
        {#                <p><input type="email" name="email" placeholder="E-mail адрес"#}
        {#                                                                 required=""#}
        {#                                                                 id="id_email"></p>#}
        {#                <p><input type="email" name="email2"#}
        {#                                                                          placeholder="Подтверждение email адреса"#}
        {#                                                                          required=""#}
        {#                                                                          id="id_email2"></p>#}
        {#                <p><input type="password" name="password1" placeholder="Пароль"#}
        {#                                                                required="" id="id_password1"></p>#}
        {#                <p><input type="password" name="password2"#}
        {#                                                                          placeholder="Пароль (ещё раз)" required=""#}
        {#                                                                          id="id_password2">#}
        {#                </p>#}
        {#                <p>#}
        {#                    <a href="{% url 'account_reset_password' %}">Забыли проль?  </a><button type="submit">Регистрация</button>#}
        {#                </p>#}
        {#            </form>#}
        {#        </div>#}
        {#    </div>#}

        <ul>

            <li class="colorlib-active"><a href="{% url 'postmodel_list' %}">Home</a></li>
            {% for name in view.get_post %}
                <div class="holder">
                    <li><a href="{{ name.get_absolute_url }}">{{ name.title }}</a>
                        <div class="block">
                            <a href="{% url 'postmodel_update' slug=name.slug %}"><span><i
                                    class="icon-edit mr-2"></i></span></a>
                        </div>
                    </li>
                </div>
            {% endfor %}
            <li><a href="{% url 'postmodel_create' %}">+</a></li>
        </ul>
        </nav>
    {% endif %}

templates/include/sidebar.html
{% if user.is_authenticated %}
    <div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
        <div class="sidebar-box pt-md-4">
            <form action="{% url 'search' %}" method="get" class="d-flex editContent">
                <input type="search" placeholder="Поиск..." name="q" class="form-control" required="">
                <button type="submit" class="btn1 btn">
                    <span class="fa fa-search" aria-hidden="true"></span>
                </button>
            </form>
        </div>
        <div class="sidebar-box ftco-animate">
            <a href="{% url 'groupmodel_create' %}"><h5 class="sidebar-heading">Добавить группу</h5></a>
        </div>
        {% for group in view.get_phone %}
            <div class="sidebar-box ftco-animate">
                <div class="poster">
                    <strong>{{ group.name }}</strong>
                    <div class="descr-group">
                        <a href="{% url 'groupmodel_delete' pk=group.id %}"><span>  <i
                                class="icon-delete mr-1"></i></span></a><a
                            href="{% url 'groupmodel_update' pk=group.id %}"><span><i
                            class="icon-edit mr-2"></i></span></a>
                    </div>
                </div>
                <ul class="categories">
                    {% for phone_number in group.phonemodel_set.all %}
               <div class="poster">
                        <li>{{ phone_number.name }}
                            <p>тел.: {{ phone_number.phone }}</p>
                            {% if phone_number.email != "" %}
                                <p>email: {{ phone_number.email }}</p>
                            {% endif %}
                        <div class="descr">
                            <a href="{% url 'phonemodel_update' pk=phone_number.id %}"><span>  <i
                                    class="icon-edit mr-1"></i></span></a><a
                                    href="{% url 'phonemodel_delete' pk=phone_number.id %}"><span
                                    style="margin-right: 15px"><i class="icon-delete mr-2"></i></span></a>
                        </div>
                        </li>
                        </div>
                    {% endfor %}
                    <li><a href="{% url 'phonemodel_create' %}">+</a></li>
                </ul>
            </div>
        {% endfor %}
    </div><!-- END COL -->
{% endif %}

templates/wiki/groupmodel_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="col-lg-8 px-md-5 py-5">
        <div class="row pt-md-4">
            <form method="POST">{% csrf_token %}
                <h1 class="mb-3">Вы хотите удалить группу - "{{ object.name }}"?</h1>
                <button type="submit" value="Удалить">Удалить</button>
                <a href="{% url 'postmodel_list' %}">
                    <button type="button" value="Не удалять">Не удалять</button>
                </a>
            </form>

        </div><!-- END-->
    </div>

{% endblock content %}

templates/wiki/phonemodel_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="col-lg-8 px-md-5 py-5">
        <div class="row pt-md-4">
            <form method="POST">{% csrf_token %}
                <h1 class="mb-3"> Вы хотите удалить контакт - "{{ object.name }}" ?</h1>
                <p class="mb-4">{{ object.phone }}</p>
                <button type="submit" value="Удалить">Удалить</button>
                <a href="{% url 'postmodel_list' %}">
                    <button type="button" value="Не удалять">Не удалять</button>
                </a>
            </form>

        </div><!-- END-->
    </div>

{% endblock content %}

templates/wiki/postmodel_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="col-lg-8 px-md-5 py-5">
        <div class="row pt-md-4">
            <form method="POST">{% csrf_token %}
                <h1 class="mb-3"> Вы хотите удалить статью - "{{ object.title }}" ?</h1>
                <button type="submit" value="Удалить">Удалить</button>
                <a href="{% url 'postmodel_list' %}">
                    <button type="button" value="Не удалять">Не удалять</button>
                </a>
                <p class="mb-4">{{ object.description|safe }}</p>
            </form>

        </div><!-- END-->
    </div>

{% endblock content %}

templates/wiki/postmodel_form.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <div class="col-lg-8 px-md-5 py-5">
        <div class="row pt-md-4">
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button type="submit" value="Соранить">Сохранить</button>
            </form>

        </div><!-- END-->
    </div>

{% endblock content %}